apiVersion: v1
kind: Service
metadata:
  namespace: dummy-dotnet-k8s-app
  labels:
    app: dummy-dotnet-k8s-app
  name: dummy-dotnet-k8s-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dummy-dotnet-k8s-app
  type: ClusterIP