apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dummy-dotnet-k8s-app
  labels:
    app: dummy-dotnet-k8s-app
  name: dummy-dotnet-k8s-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-dotnet-k8s-app
  template:
    metadata:
      labels:
        app: dummy-dotnet-k8s-app
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        image: dummy-dotnet-k8s-app
        imagePullPolicy: Never
        name: container
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
      # imagePullSecrets:
      # - name: acr-srcrdev-registry
      restartPolicy: Always